# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nsfw_detector.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13nsfw_detector.proto\x12\rnsfw_detector\"\'\n\x13NSFWDetectorRequest\x12\x10\n\x08video_id\x18\x01 \x01(\t\"*\n\x14NSFWDetectorResponse\x12\x12\n\ncategories\x18\x01 \x03(\t2g\n\x0cNSFWDetector\x12W\n\nDetectNSFW\x12\".nsfw_detector.NSFWDetectorRequest\x1a#.nsfw_detector.NSFWDetectorResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nsfw_detector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NSFWDETECTORREQUEST']._serialized_start=38
  _globals['_NSFWDETECTORREQUEST']._serialized_end=77
  _globals['_NSFWDETECTORRESPONSE']._serialized_start=79
  _globals['_NSFWDETECTORRESPONSE']._serialized_end=121
  _globals['_NSFWDETECTOR']._serialized_start=123
  _globals['_NSFWDETECTOR']._serialized_end=226
# @@protoc_insertion_point(module_scope)
