name: Deploy to Fly on push to main
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  deploy:
    name: Deploy

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set Fly secrets
        run: |
          flyctl secrets set --stage --app "yral-nsfw-classification" "SERVICE_CRED=$SERVICE_CRED"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKENS }}
          SERVICE_CRED: ${{ secrets.SERVICE_CRED }}
      - name: Deploy a docker container to fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKENS }}
